// Cross-platform git pre-commit hook setup (replaces scripts/setup-hooks.sh).
// Run via: `npm run setup-hooks` → `node scripts/setup-hooks.ts`
//
// Pure Node.js, no shell-isms, no Python. Installs a `.git/hooks/pre-commit`
// file (POSIX `sh` — git runs hooks via sh.exe on Windows, so this works
// cross-platform without any bash requirement). The hook runs the project's
// `biome check` (lint + format), `npm run typecheck` and `npm run validate`
// gates before each commit.
//
// Unlike the old setup-hooks.sh, this does NOT install the Python pre-commit
// framework, black/flake8/isort, or detect-secrets (the project has dropped
// Python). Linting/formatting is Biome (`npm run lint` / `npm run format`)
// and is part of the gate.

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync, chmodSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const GREEN = '\x1b[32m';
const RED = '\x1b[31m';
const RESET = '\x1b[0m';

const ok = (m: string) => console.log(`  ${GREEN}✓${RESET} ${m}`);
const fail = (m: string) => console.log(`  ${RED}✗${RESET} ${m}`);

console.log('🔧 Setting up Git hooks for code quality...');
console.log('==========================================');
console.log('');

// scripts/setup-hooks.ts → scripts → <project root>
const _HERE = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = dirname(_HERE);
const GIT_DIR = join(PROJECT_ROOT, '.git');
const HOOKS_DIR = join(GIT_DIR, 'hooks');
const HOOK_FILE = join(HOOKS_DIR, 'pre-commit');

// 1. Sanity checks: node + git repo present.
if (!existsSync(GIT_DIR)) {
  fail('Not a git repository (no .git directory found)');
  console.log('  Run `git init` first, then re-run this script.');
  process.exit(1);
}

const nodeOk = spawnSync(process.execPath, ['--version'], { stdio: 'ignore' }).status === 0;
if (!nodeOk) {
  fail('Node.js is required but not available');
  process.exit(1);
}
ok('Node.js available');

// 2. Ensure node_modules present (hook calls npm scripts).
if (!existsSync(join(PROJECT_ROOT, 'node_modules'))) {
  console.log('📦 Installing dependencies (npm install)...');
  const npmInstall = spawnSync(process.platform === 'win32' ? 'npm.cmd' : 'npm', ['install'], {
    cwd: PROJECT_ROOT,
    stdio: 'inherit',
  });
  if (npmInstall.status !== 0) {
    fail('npm install failed');
    process.exit(1);
  }
}

// 3. Write the pre-commit hook (POSIX sh — git runs it via sh on all OSes).
if (!existsSync(HOOKS_DIR)) {
  mkdirSync(HOOKS_DIR, { recursive: true });
}

const hook = `#!/bin/sh
# Auto-generated by scripts/setup-hooks.ts — do not edit by hand.
# Runs the project's static checks before each commit. Skip with:
#   git commit --no-verify

set -e
echo "🔍 Running pre-commit checks (biome + typecheck + validate)..."
npx @biomejs/biome check .
npm run typecheck
npm run validate
echo "✅ Pre-commit checks passed."
`;
writeFileSync(HOOK_FILE, hook, 'utf8');

// chmod +x — only meaningful on unix, but harmless on Windows (git uses sh.exe).
try {
  chmodSync(HOOK_FILE, 0o755);
} catch {
  /* Windows: chmod is a no-op; git runs hooks via sh.exe regardless */
}
ok(`pre-commit hook installed at ${HOOK_FILE.replace(/\\/g, '/')}`);

// 4. Optional: run the hook once to verify.
console.log('');
console.log('🧪 Testing hook (npm run typecheck && npm run validate)...');
// shell + single-string: reliable on Windows (npm.cmd) and unix. Null stdin
// so validate.ts's server spawn (on its own pipe) isn't raced by an
// inherited parent stdin.
const testRun = spawnSync('npm run validate', {
  cwd: PROJECT_ROOT,
  stdio: ['ignore', 'inherit', 'inherit'],
  shell: true,
});
if (testRun.status === 0) {
  ok('Hook test passed');
} else {
  fail('Hook test reported errors (see above) — fix before committing');
}

console.log('');
console.log(`${GREEN}✅ Git hooks setup complete!${RESET}`);
console.log('');
console.log('The following checks will run before each commit:');
console.log('  ✓ Biome (lint + format check)');
console.log('  ✓ TypeScript typecheck (tsc, no emit)');
console.log('  ✓ Validation (node --check + .env tracking + server startup)');
console.log('');
console.log('To skip hooks temporarily: git commit --no-verify');
console.log('To run hooks manually:    .git/hooks/pre-commit');
